version: '3.8'

services:
  load-balancer:
    build:
      context: .
      dockerfile: Dockerfile
    image: loadbalancer
    environment:
      - ENV=production
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
